spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/member?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: ENC(20AqFhGm1rJcqi/G06kHHpWdi8a94A1S)
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379
    password:


image:
  dir: C:\Users\82108\Desktop\image\

